make -k other_keyword append to the defaults
gmarty/xgettext pull request #82
Opened 2021-03-26 18:59 UTC by jsut

- This is how xgettext works, which is how the docs say it works.

2021-03-27 07:09 UTC, smhg requested changes
Thank you, this is a great idea. I've left some individual line comments.
On top of that, I think 2 things are still missing:

- `xgettext` allows to reset the default keywords by passing `-k` (without a word). It would be a very good idea to add this behavior in this PR since this provides the easiest upgrade path from the old usage. Otherwise things will break much more for existing users.
- It would be great to have tests for the actual differences in keywords passed to the parsers. Now we only test the resulting output. This would require to expose (a part of) the current `getParser` function somehow. I don't know what the best approach is; feedback on this is very much appreciated.

2021-03-27 14:30 UTC, jsut commented on test/fixtures/keyword.hbs
> +{{$ "regex escaped keyword"}}
vim being particular about whether their should be a newline at the end of the file.  I'll fix it.

2021-03-27 14:35 UTC, smhg commented on test/fixtures/keyword.hbs
> +{{$ "regex escaped keyword"}}
Strange, as I don't see a newline at the end of the file in master either. Can it be a different line ending (should be Unix-style)?

2021-03-27 14:51 UTC, jsut commented
>     * `xgettext` allows to reset the default keywords by passing `-k` (without a word). It would be a very good idea to add this behavior in this PR since this provides the easiest upgrade path from the old usage. Otherwise things will break much more for existing users.

I haven't looked at the code for this yet, but it seems like another PR to me.  There are other issues with -k as well.  With gnu xgettext there doesn't have to be (and perhaps cannot be, i haven't tested it) a space after the -k before the identifier. I think another PR that adds this functionality and adds tests for createKeywordSpec could be the right thing to do.
 
>     * It would be great to have tests for the actual differences in keywords passed to the parsers. Now we only test the resulting output. This would require to expose (a part of) the current `getParser` function somehow. I don't know what the best approach is; feedback on this is very much appreciated.

Perhaps add more functionality to keyword-spec.js, a function that will take a bunch of specs and combine them. Then you could test that function directly, and the code currently in this PR gets even simpler.

2021-03-27 15:16 UTC, smhg commented
> I haven't looked at the code for this yet, but it seems like another PR to me. There are other issues with -k as well. With gnu xgettext there doesn't have to be (and perhaps cannot be, i haven't tested it) a space after the -k before the identifier. I think another PR that adds this functionality and adds tests for createKeywordSpec could be the right thing to do.

I prefer this in the same PR, but separate is fine too. It's just that this functionality is crucial for this PR to move ahead.
Someone who would install a version with the current change and uses `-k somekeyword` would suddenly also get all default keywords and quite realistically a much different output. There would be no migration path. When you can disable the defaults with -k, you'd only need to change this to `-k -k somekeyword`. The same way `xgettext` handles this.

You don't need to worry about the exact way to specify parameters as that's something that is handled by the optstring parser (yargs). We stick to their format, not xgettext's in that area.

> Perhaps add more functionality to keyword-spec.js, a function that will take a bunch of specs and combine them. Then you could test that function directly, and the code currently in this PR gets even simpler.

Yes, this would be great to have. That can definitely be in a separate PR of course.

2021-03-27 15:47 UTC, jsut commented
This change i just pushed causes test failures, but I think the bug is actually in the handlebars parser? Something weird is going on anyway.

This is what i see in a bunch of console.logs with the previous version
```
defaults
{ _: { msgid: 0 },
  gettext: { msgid: 0 },
  dgettext: { msgid: 1 },
  dcgettext: { msgid: 1 },
  ngettext: { msgid: 0, msgid_plural: 1 },
  dngettext: { msgid: 1, msgid_plural: 2 },
  pgettext: { msgctxt: 0, msgid: 1 },
  dpgettext: { msgctxt: 1, msgid: 2 } }
overrides
{ npgettext: [ 1, 2, msgctxt: 0, msgid: 1, msgid_plural: 2 ] }
combined
{ npgettext: [ 1, 2, msgctxt: 0, msgid: 1, msgid_plural: 2 ],
  _: { msgid: 0 },
  gettext: { msgid: 0 },
  dgettext: { msgid: 1 },
  dcgettext: { msgid: 1 },
  ngettext: { msgid: 0, msgid_plural: 1 },
  dngettext: { msgid: 1, msgid_plural: 2 },
  pgettext: { msgctxt: 0, msgid: 1 },
  dpgettext: { msgctxt: 1, msgid: 2 } }
```

This is what i get with this change
```
defaults
{ _: { msgid: 0 },
  gettext: { msgid: 0 },
  dgettext: { msgid: 1 },
  dcgettext: { msgid: 1 },
  ngettext: { msgid: 0, msgid_plural: 1 },
  dngettext: { msgid: 1, msgid_plural: 2 },
  pgettext: { msgctxt: 0, msgid: 1 },
  dpgettext: { msgctxt: 1, msgid: 2 } }
overrides
{ npgettext: [ 1, 2, msgctxt: 0, msgid: 1, msgid_plural: 2 ] }
combined
{ _: { msgid: 0 },
  gettext: { msgid: 0 },
  dgettext: { msgid: 1 },
  dcgettext: { msgid: 1 },
  ngettext: { msgid: 0, msgid_plural: 1 },
  dngettext: { msgid: 1, msgid_plural: 2 },
  pgettext: { msgctxt: 0, msgid: 1 },
  dpgettext: { msgctxt: 1, msgid: 2 },
  npgettext: [ 1, 2, msgctxt: 0, msgid: 1, msgid_plural: 2 ] }
```

so the only thing different is the order of the keys in the object.  I'm also not sure what's up with the user specified stuff being an array, and the defaults being objects.  This seems like asking for problems to me.  I haven't dug into this any further yet in case you have an idea off the top of you head about why the order of the keys would cause these test failures.

2021-03-27 17:06 UTC, jsut commented on test/fixtures/keyword.hbs
> +{{$ "regex escaped keyword"}}
there was no newline before.

2021-03-28 06:08 UTC, smhg commented
@jsut please also run `npm run lint` during or after development. Please make sure that passes.

2021-03-28 12:53 UTC, jsut commented
> @jsut please also run `npm run lint` during or after development (or make your editor run eslint). Please make sure that passes.

done

2021-04-01 01:16 UTC, jsut commented
@smhg do you need anything else here?

2021-04-08 07:29 UTC, smhg commented
@jsut there are some minor changes in master. Could you merge them into your branch? I'll check things in the next few days and release this.

2021-04-08 13:03 UTC, jsut commented
@smhg it's rebased

2021-04-08 13:10 UTC, smhg commented
@jsut thanks!
Running `./bin/xgettext-template` with only `-k` (and no new keywords) throws an error.
Can you add a test for this and handle this scenario?

2021-04-08 14:36 UTC, jsut commented
@smhg yup, maybe this afternoon.

2021-04-17 14:34 UTC, smhg commented
Thank you for your ongoing efforts @jsut! I've had some time to look at the actual changes to the code.

- The implementation you proposed to enable this new behavior is not great. I understand why you chose this route. It does work. It however makes to code harder to interpret. For instance: adding a property to the keywordSpec to later delete that property again feels like a hack. Also, the `-k` case (reset) should probably not be passed on to createKeywordSpec but 'detected' early on.
- The tests you added are great.
- Don't force push changes. Just add new commits and in the end everything will be squashed into one commit into master. It is not important in how many steps you create this.

Would you be open to further improve the PR? I'm happy to add comments to the code if you're open to this.
If you don't, feel free to only keep the changes to the tests and fixtures. We can definitely use those.

2021-04-17 15:03 UTC, jsut commented
If you have a cleaner way to implement it @smhg let me know. I just tried to make it work despite it seeming like a pretty pointless thing to implement since running the thing with only a -k will never result in any output other than an empty po file anyway.

I dug into how yargs works to try to find a cleaner way to handle this, but it seemed like a dead end.

2021-04-17 18:22 UTC, jsut commented
@smhg this seems cleaner, not loving all the spec.spec, particularly in the tests, but yeah...

2021-04-18 12:07 UTC, smhg commented
@jsut thank you for your efforts. I don't think this is moving in the right direction. I'd love to offer more timely feedback, but I have to acknowledge I don't have the time for that kind of followup currently.

In general:
- xgettext handles `--keyword` and `--keyword=""` as ways to disable the defaults. Currently the first one would work, but **only in the right order** (when another parameter follows). That's a hard problem as far as I can see, but we can't move ahead that way. I think an acceptable workaround would be to only support `--keyword=""` for now.
- The way you implement the new feature is rather strange to me. I think it is better to 'filter' out a possible reset early on and _not_ pass that to `createKeywordSpec`. So it does not need to handle that and so there is no need to return a wrapper object. I might be wrong about this.

2021-04-18 12:31 UTC, smhg commented
I've added an alternative solution to the [v5](https://github.com/gmarty/xgettext/tree/v5) branch based on your tests.
This does not handle the `-k` or `--keyword` (boolean) use however. That would still need to be added for a v5 release.

2021-04-18 14:09 UTC, jsut commented
Given your branched changes, i'm not sure if i should be doing anything else here or not.

>     * xgettext handles `--keyword` and `--keyword=""` as ways to disable the defaults. Currently the first one would work, but **only in the right order** (when another parameter follows). That's a hard problem as far as I can see, but we can't move ahead that way. I think an acceptable workaround would be to only support `--keyword=""` for now.

I'm not sure if you're talking about gnu xgettext here, or this package. In any case, in this branch, both of them support -k., in any position in the parameter list on the CLI, with the one caveat that in xgettext-template, if you do -k <filename>, or --keyword <filename> then yargs will slurp up the filename as the 'keyword'. This is a yargs problem, and i think it's actually impossible to fix without a significant change to yargs, or some serious massaging of what you pass into yargs.  Neither of which seem reasonable to me.  What does seem reasonable though, is documenting this shortcoming of -k/--keyword.  It all goes back to my original complaint about the space after -k. Maybe yargs does handle this, but i'm not that familiar with it and my dive into the docs was not fruitful.

>     * The way you implement the new feature is rather strange to me. I think it is better to 'filter' out a possible reset early on and _not_ pass that to `createKeywordSpec`. So it does not need to handle that and so there is no need to return a wrapper object. I might be wrong about this.

This seems like a reasonable improvement to me.  Do you think that the code that does this filtering should live in index.js, or should keyword-spec.js be expanded to have more exports, and one of them is the function that does this?

2023-03-03 19:44 UTC, closed without merging